---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-loadbalancer
  namespace: vaccination-system-dev
  labels:
    svc: vms
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

spec:
  type: LoadBalancer
  selector:
    vms: frontend
  ports:
  - name: http-web
    protocol: TCP
    port: 80
    targetPort: 3000
  - name: https-web
    protocol: TCP
    port: 443
    targetPort: 3000